forward: "kb_w";
back: "kb_s";
left: "kb_a, ga_dpleft";
right: "kb_d, ga_dpright";
jump: "kb_space";
interact: "kb_e";

sunDown: "kb_down";
sunUp: "kb_up";
sunLeft: "kb_left";
sunRight: "kb_right";

toggleEnvironment: "kb_f1";
toggleGUI: "kb_g";
screenshot: "kb_f12";
