fxaa.enabled: true;

ssao.enabled: true;
ssao.samples: 20;
ssao.radius: 0.2;
ssao.power: 5.0;
ssao.denoise: 1.0;
ssao.occlusionBufferDetail: 0.5;

glow.enabled: true;
glow.viewScale: 0.33;
glow.threshold: 0.0;
glow.intensity: 0.2;
glow.radius: 10;

hdr.tonemapper: "AgX_Punchy";
hdr.exposure: 1.0;
hdr.autoexposure: true;
hdr.keyValue: 0.2;
hdr.exposureAdaptationSpeed: 2.0;

vignette.enabled: true;
vignette.strength: 1.0;
vignette.size: [0.5, 0.3];
vignette.roundness: 1.0;
vignette.feathering: 0.4;

motionBlur.enabled: true;
motionBlur.samples: 16;
motionBlur.framerate: 30;
motionBlur.randomness: 0.5;
motionBlur.minDistance: 0.01;
motionBlur.maxDistance: 1.0;
motionBlur.radialBlurAmount: 0.0;

lensDistortion.enabled: true;
lensDistortion.scale: 1.0;
lensDistortion.dispersion: 0.02;

dof.enabled: true;
dof.autofocus: true;
dof.focalDepth: 1.0;
dof.focalLength: 20.0;
dof.fStop: 16.0;
dof.manual: false;
dof.nearStart: 1.0;
dof.nearDistance: 2.0;
dof.farStart: 1.0;
dof.farDistance: 3.0;
dof.circleOfConfusion: 0.03;
dof.pentagonBokeh: false;
dof.pentagonBokehFeather: 0.4;

filmGrain.enabled: true;
filmGrain.colored: true;

sharpening.enabled: true;
sharpening.strength: 0.8;

cc.brightness: 0.0;
cc.contrast: 1.0;
cc.saturation: 1.0;

lut.enabled: true;
lut.file: "data/lut.png";
